"""Generated from `base_model_IM.ode` -- do not edit by hand.

Regenerate with `python3 tools/generate_membrane_models.py`.

Generated by gotranx with singularity guarding on (the default), which adds one guard to
this model (`ibarca_j`, |V_m| < 0.019 mV) at a cost of roughly 10% per step. The scheme is
`generalized_rush_larsen`; the backend is numpy, so this module imports numpy and nothing
else, which is what keeps `sknm`'s runtime dependencies to numpy + scipy.
"""

import numpy

parameter = {
    "B_tot_c": 0,
    "B_tot_d": 1,
    "B_tot_s": 2,
    "B_tot_sl": 3,
    "Cli": 4,
    "Clo": 5,
    "Cm": 6,
    "E_f": 7,
    "Frdy": 8,
    "J_SERCA_bar": 9,
    "K_RyR": 10,
    "K_c": 11,
    "K_i": 12,
    "K_n": 13,
    "Kdact": 14,
    "KmCai": 15,
    "KmCao": 16,
    "KmKo": 17,
    "KmNai": 18,
    "KmNaip": 19,
    "KmNao": 20,
    "KmPCa": 21,
    "Ko": 22,
    "Nao": 23,
    "Q10CaL": 24,
    "Q10K_Nai": 25,
    "Q10Kr_act": 26,
    "Q10Kr_inact": 27,
    "Q10Ks": 28,
    "Q10Na": 29,
    "Q10NaCa": 30,
    "Q10NaK": 31,
    "Q10NaL": 32,
    "Q10SERCA": 33,
    "Q10f": 34,
    "Q10pCa": 35,
    "Q10to": 36,
    "R": 37,
    "SQT1": 38,
    "Temp": 39,
    "Vc": 40,
    "Vd": 41,
    "Vn": 42,
    "Vs": 43,
    "Vsl": 44,
    "alpha_RyR": 45,
    "alpha_d_c": 46,
    "alpha_n_s": 47,
    "alpha_sl_c": 48,
    "beta_RyR": 49,
    "ce": 50,
    "chi": 51,
    "eta_RyR": 52,
    "g_CaL": 53,
    "g_K1": 54,
    "g_Kr": 55,
    "g_Ks": 56,
    "g_Na": 57,
    "g_NaCa": 58,
    "g_NaK": 59,
    "g_NaL": 60,
    "g_bCa": 61,
    "g_bCl": 62,
    "g_f": 63,
    "g_pCa": 64,
    "g_to": 65,
    "gamma_RyR": 66,
    "k_off_c": 67,
    "k_off_d": 68,
    "k_off_s": 69,
    "k_off_sl": 70,
    "k_on_c": 71,
    "k_on_d": 72,
    "k_on_s": 73,
    "k_on_sl": 74,
    "ksat": 75,
    "nu": 76,
    "pNaK": 77,
    "stim_amplitude": 78,
    "stim_duration": 79,
    "stim_period": 80,
    "stim_start": 81,
    "thL": 82,
}


def parameter_index(name: str) -> int:
    """Return the index of the parameter with the given name

    Arguments
    ---------
    name : str
        The name of the parameter

    Returns
    -------
    int
        The index of the parameter

    Raises
    ------
    KeyError
        If the name is not a valid parameter
    """

    return parameter[name]


state = {
    "f_Ca": 0,
    "f": 1,
    "bc": 2,
    "bd": 3,
    "bs": 4,
    "bsl": 5,
    "cc": 6,
    "cn": 7,
    "q": 8,
    "r": 9,
    "xf": 10,
    "m": 11,
    "x_Ks": 12,
    "hL": 13,
    "Xr1": 14,
    "Xr2": 15,
    "j": 16,
    "d": 17,
    "mL": 18,
    "r_RyR": 19,
    "cs": 20,
    "cd": 21,
    "csl": 22,
    "Na_i": 23,
    "V_m": 24,
}


def state_index(name: str) -> int:
    """Return the index of the state with the given name

    Arguments
    ---------
    name : str
        The name of the state

    Returns
    -------
    int
        The index of the state

    Raises
    ------
    KeyError
        If the name is not a valid state
    """

    return state[name]


monitor = {
    "FoRT": 0,
    "Qpow": 1,
    "GNaL": 2,
    "Xr1_inf": 3,
    "aj": 4,
    "alpha_Xr1": 5,
    "alpha_Xr2": 6,
    "beta_Xr1": 7,
    "beta_Xr2": 8,
    "bj": 9,
    "dss": 10,
    "fss": 11,
    "hLss": 12,
    "jss": 13,
    "mLss": 14,
    "mss": 15,
    "q_inf": 16,
    "r_inf": 17,
    "tauf": 18,
    "tm": 19,
    "xf_inf": 20,
    "xsss": 21,
    "I_f": 22,
    "J_c_b": 23,
    "df_Ca_dt": 24,
    "J_d_b": 25,
    "J_d_c": 26,
    "J_leak": 27,
    "J_n_s": 28,
    "J_s_b": 29,
    "J_sl_b": 30,
    "J_sl_c": 31,
    "Ka_sl": 32,
    "Xr2_infinity": 33,
    "sigma": 34,
    "i_Stim": 35,
    "p": 36,
    "s3_sl": 37,
    "eca_sl": 38,
    "ecl": 39,
    "ek": 40,
    "eks": 41,
    "ena": 42,
    "ibarca_j": 43,
    "s1_sl": 44,
    "s2_sl": 45,
    "I_pCa": 46,
    "J_SERCA": 47,
    "tau_q": 48,
    "tau_r": 49,
    "tau_xf": 50,
    "taum": 51,
    "tauxs": 52,
    "thLc": 53,
    "tau_Xr1": 54,
    "tau_Xr2": 55,
    "tauj": 56,
    "taud": 57,
    "df_dt": 58,
    "tmL": 59,
    "dbc_dt": 60,
    "dbd_dt": 61,
    "dbs_dt": 62,
    "dbsl_dt": 63,
    "fNaK": 64,
    "J_RyR_active": 65,
    "I_bCa": 66,
    "I_bCl": 67,
    "I_Kr": 68,
    "I_to": 69,
    "aK1": 70,
    "bK1": 71,
    "I_Ks": 72,
    "I_Na": 73,
    "I_NaL": 74,
    "I_CaL": 75,
    "I_NaCa": 76,
    "J_pCa": 77,
    "dcc_dt": 78,
    "dcn_dt": 79,
    "dq_dt": 80,
    "dr_dt": 81,
    "dxf_dt": 82,
    "dm_dt": 83,
    "dx_Ks_dt": 84,
    "dhL_dt": 85,
    "dXr1_dt": 86,
    "dXr2_dt": 87,
    "dj_dt": 88,
    "dd_dt": 89,
    "dmL_dt": 90,
    "I_NaK": 91,
    "J_RyR": 92,
    "dr_RyR_dt": 93,
    "J_bCa": 94,
    "K1ss": 95,
    "J_CaL": 96,
    "J_NaCa": 97,
    "I_Na_tot": 98,
    "dcs_dt": 99,
    "I_K1": 100,
    "dcd_dt": 101,
    "J_e_sl": 102,
    "J_Na": 103,
    "I_tot": 104,
    "dcsl_dt": 105,
    "dNa_i_dt": 106,
    "dV_m_dt": 107,
}


def monitor_index(name: str) -> int:
    """Return the index of the monitor with the given name

    Arguments
    ---------
    name : str
        The name of the monitor

    Returns
    -------
    int
        The index of the monitor

    Raises
    ------
    KeyError
        If the name is not a valid monitor
    """

    return monitor[name]


def init_parameter_values(**values):
    """Initialize parameter values"""
    # B_tot_c=0.160901953786, B_tot_d=4.35776124837
    # B_tot_s=64.8077313861, B_tot_sl=2.23474935814, Cli=15.0
    # Clo=150.0, Cm=0.01, E_f=-17.0, Frdy=96.485
    # J_SERCA_bar=0.00050997272922, K_RyR=0.015, K_c=0.00025
    # K_i=180.0, K_n=1.7, Kdact=0.00015, KmCai=0.0036, KmCao=1.3
    # KmKo=1.5, KmNai=12.3, KmNaip=11, KmNao=87.5, KmPCa=0.0005
    # Ko=5.4, Nao=130.0, Q10CaL=1.8, Q10K_Nai=1.5, Q10Kr_act=4.55
    # Q10Kr_inact=3.08, Q10Ks=2.0, Q10Na=2, Q10NaCa=1.6, Q10NaK=1.6
    # Q10NaL=2.2, Q10SERCA=2.6, Q10f=4.5, Q10pCa=2.35, Q10to=2.0
    # R=8.314, SQT1=0, Temp=296.0, Vc=0.917, Vd=0.001, Vn=0.05
    # Vs=0.004, Vsl=0.028, alpha_RyR=0.00943255224019
    # alpha_d_c=0.00487747303306, alpha_n_s=0.0133297071619
    # alpha_sl_c=0.174311555194, beta_RyR=0.0477309872395, ce=1.8
    # chi=0.9, eta_RyR=1e-05, g_CaL=0.546805688346
    # g_K1=0.0454091576915, g_Kr=0.125730144, g_Ks=0.0368232692938
    # g_Na=1.24186359959, g_NaCa=13.4758307874
    # g_NaK=0.100590496631, g_NaL=0.0541973343896
    # g_bCa=5.614377099e-05, g_bCl=0.0123835635
    # g_f=0.00060989695668, g_pCa=0.766545241191
    # g_to=0.0672247871421, gamma_RyR=0.001, k_off_c=0.03
    # k_off_d=1.0, k_off_s=65.0, k_off_sl=0.15, k_on_c=40.0
    # k_on_d=100.0, k_on_s=100.0, k_on_sl=100.0, ksat=0.3, nu=0.3
    # pNaK=0.018, stim_amplitude=5.0, stim_duration=20.0
    # stim_period=5000.0, stim_start=0.0, thL=200

    parameters = numpy.array(
        [
            0.160901953786,
            4.35776124837,
            64.8077313861,
            2.23474935814,
            15.0,
            150.0,
            0.01,
            -17.0,
            96.485,
            0.00050997272922,
            0.015,
            0.00025,
            180.0,
            1.7,
            0.00015,
            0.0036,
            1.3,
            1.5,
            12.3,
            11,
            87.5,
            0.0005,
            5.4,
            130.0,
            1.8,
            1.5,
            4.55,
            3.08,
            2.0,
            2,
            1.6,
            1.6,
            2.2,
            2.6,
            4.5,
            2.35,
            2.0,
            8.314,
            0,
            296.0,
            0.917,
            0.001,
            0.05,
            0.004,
            0.028,
            0.00943255224019,
            0.00487747303306,
            0.0133297071619,
            0.174311555194,
            0.0477309872395,
            1.8,
            0.9,
            1e-05,
            0.546805688346,
            0.0454091576915,
            0.125730144,
            0.0368232692938,
            1.24186359959,
            13.4758307874,
            0.100590496631,
            0.0541973343896,
            5.614377099e-05,
            0.0123835635,
            0.00060989695668,
            0.766545241191,
            0.0672247871421,
            0.001,
            0.03,
            1.0,
            65.0,
            0.15,
            40.0,
            100.0,
            100.0,
            100.0,
            0.3,
            0.3,
            0.018,
            5.0,
            20.0,
            5000.0,
            0.0,
            200,
        ],
        dtype=numpy.float64,
    )

    for key, value in values.items():
        parameters[parameter_index(key)] = value

    return parameters


def init_state_values(**values):
    """Initialize state values"""
    # f_Ca=0.0229797667091, f=0.99105533754, bc=0.0275492882673
    # bd=0.0711052624778, bs=38.0260204274, bsl=0.255547827638
    # cc=0.00015488893215, cn=0.92348378818, q=0.857503916787
    # r=0.00516700066747, xf=0.265364816616, m=0.0109284403259
    # x_Ks=0.00559232069994, hL=0.175629143229
    # Xr1=0.00672841686988, Xr2=0.575146421688, j=0.422428440152
    # d=6.87003785e-06, mL=0.00127186232071, r_RyR=0.999999976809
    # cs=0.922902611757, cd=0.00016587400295, csl=0.00019366401941
    # Na_i=16.1449457083, V_m=-76.3299880038

    states = numpy.array(
        [
            0.0229797667091,
            0.99105533754,
            0.0275492882673,
            0.0711052624778,
            38.0260204274,
            0.255547827638,
            0.00015488893215,
            0.92348378818,
            0.857503916787,
            0.00516700066747,
            0.265364816616,
            0.0109284403259,
            0.00559232069994,
            0.175629143229,
            0.00672841686988,
            0.575146421688,
            0.422428440152,
            6.87003785e-06,
            0.00127186232071,
            0.999999976809,
            0.922902611757,
            0.00016587400295,
            0.00019366401941,
            16.1449457083,
            -76.3299880038,
        ],
        dtype=numpy.float64,
    )

    for key, value in values.items():
        states[state_index(key)] = value

    return states


def rhs(t, states, parameters):

    # Assign states
    f_Ca = states[0]
    f = states[1]
    bc = states[2]
    bd = states[3]
    bs = states[4]
    bsl = states[5]
    cc = states[6]
    cn = states[7]
    q = states[8]
    r = states[9]
    xf = states[10]
    m = states[11]
    x_Ks = states[12]
    hL = states[13]
    Xr1 = states[14]
    Xr2 = states[15]
    j = states[16]
    d = states[17]
    mL = states[18]
    r_RyR = states[19]
    cs = states[20]
    cd = states[21]
    csl = states[22]
    Na_i = states[23]
    V_m = states[24]

    # Assign parameters
    B_tot_c = parameters[0]
    B_tot_d = parameters[1]
    B_tot_s = parameters[2]
    B_tot_sl = parameters[3]
    Cli = parameters[4]
    Clo = parameters[5]
    Cm = parameters[6]
    E_f = parameters[7]
    Frdy = parameters[8]
    J_SERCA_bar = parameters[9]
    K_RyR = parameters[10]
    K_c = parameters[11]
    K_i = parameters[12]
    K_n = parameters[13]
    Kdact = parameters[14]
    KmCai = parameters[15]
    KmCao = parameters[16]
    KmKo = parameters[17]
    KmNai = parameters[18]
    KmNaip = parameters[19]
    KmNao = parameters[20]
    KmPCa = parameters[21]
    Ko = parameters[22]
    Nao = parameters[23]
    Q10CaL = parameters[24]
    Q10K_Nai = parameters[25]
    Q10Kr_act = parameters[26]
    Q10Kr_inact = parameters[27]
    Q10Ks = parameters[28]
    Q10Na = parameters[29]
    Q10NaCa = parameters[30]
    Q10NaK = parameters[31]
    Q10NaL = parameters[32]
    Q10SERCA = parameters[33]
    Q10f = parameters[34]
    Q10pCa = parameters[35]
    Q10to = parameters[36]
    R = parameters[37]
    SQT1 = parameters[38]
    Temp = parameters[39]
    Vc = parameters[40]
    Vd = parameters[41]
    Vn = parameters[42]
    Vs = parameters[43]
    Vsl = parameters[44]
    alpha_RyR = parameters[45]
    alpha_d_c = parameters[46]
    alpha_n_s = parameters[47]
    alpha_sl_c = parameters[48]
    beta_RyR = parameters[49]
    ce = parameters[50]
    chi = parameters[51]
    eta_RyR = parameters[52]
    g_CaL = parameters[53]
    g_K1 = parameters[54]
    g_Kr = parameters[55]
    g_Ks = parameters[56]
    g_Na = parameters[57]
    g_NaCa = parameters[58]
    g_NaK = parameters[59]
    g_NaL = parameters[60]
    g_bCa = parameters[61]
    g_bCl = parameters[62]
    g_f = parameters[63]
    g_pCa = parameters[64]
    g_to = parameters[65]
    gamma_RyR = parameters[66]
    k_off_c = parameters[67]
    k_off_d = parameters[68]
    k_off_s = parameters[69]
    k_off_sl = parameters[70]
    k_on_c = parameters[71]
    k_on_d = parameters[72]
    k_on_s = parameters[73]
    k_on_sl = parameters[74]
    ksat = parameters[75]
    nu = parameters[76]
    pNaK = parameters[77]
    stim_amplitude = parameters[78]
    stim_duration = parameters[79]
    stim_period = parameters[80]
    stim_start = parameters[81]
    thL = parameters[82]

    # Assign expressions

    values = numpy.zeros_like(states, dtype=numpy.float64)
    FoRT = Frdy / (R * Temp)
    Qpow = 0.1 * Temp - 31.0
    GNaL = g_NaL
    Xr1_inf = 1.0 / (1.19299933802777 * numpy.exp((-0.065359477124183) * V_m) + 1.0)
    aj = numpy.where(
        (V_m >= -40.0),
        0.0,
        ((V_m + 38.0) * ((-25000.0) * numpy.exp(0.2 * V_m) - 7e-06 * numpy.exp((-0.04) * V_m)))
        / (19623624323.6513 * numpy.exp(0.3 * V_m) + 1.0),
    )
    alpha_Xr1 = 450.0 / (0.0111089965382423 * numpy.exp((-0.1) * V_m) + 1.0)
    alpha_Xr2 = 3.0 / (0.0497870683678639 * numpy.exp((-0.05) * V_m) + 1.0)
    beta_Xr1 = 6.0 / (13.5813245225782 * numpy.exp(0.0869565217391304 * V_m) + 1.0)
    beta_Xr2 = 1.12 / (0.0497870683678639 * numpy.exp(0.05 * V_m) + 1.0)
    bj = numpy.where(
        (V_m >= -40.0),
        (0.6 * numpy.exp(0.09 * V_m)) / (numpy.exp(-V_m - 40.0) + 1.0),
        (0.02 * numpy.exp((-0.01) * V_m)) / (0.00369786371648293 * numpy.exp((-0.14) * V_m) + 1.0),
    )
    dss = 1.0 / (0.434598208507078 * numpy.exp((-0.166666666666667) * V_m) + 1.0)
    fss = 0.6 / (12.1824939607035 * numpy.exp((-0.05) * V_m) + 1.0) + 1.0 / (
        48.8565712749872 * numpy.exp(0.111111111111111 * V_m) + 1.0
    )
    hLss = 1.0 / (124658.506952443 * numpy.exp(0.133333333333333 * V_m) + 1.0)
    jss = 1.0 / (
        (numpy.exp(V_m / 7.0 + 72.0 / 7.0) + 1.0) * (numpy.exp(V_m / 7.0 + 72.0 / 7.0) + 1.0)
    )
    mLss = 1.0 / (numpy.exp(-V_m / 5.0 + (-43.0) / 5.0) + 1.0)
    mss = 1.0 / (
        (numpy.exp(-V_m / 9.0 + (-19.0) / 3.0) + 1.0)
        * (numpy.exp(-V_m / 9.0 + (-19.0) / 3.0) + 1.0)
    )
    q_inf = 1.0 / (58.9637634804245 * numpy.exp(0.0769230769230769 * V_m) + 1.0)
    r_inf = 1.0 / (3.28489055021172 * numpy.exp((-0.0533333333333333) * V_m) + 1.0)
    tauf = 1.0 / (0.02 + 0.02 * numpy.exp(-(0.034 * V_m + 0.493) * (0.034 * V_m + 0.493)))
    tm = 1.0 / (
        6.8 * numpy.exp(V_m / 35.0 + 12.0 / 35.0) + 8.6 * numpy.exp(-V_m / 6.0 + (-77.0) / 6.0)
    )
    xf_inf = 1.0 / (5956538.01318462 * numpy.exp(0.2 * V_m) + 1.0)
    xsss = 1.0 / (0.762289730789954 * numpy.exp((-V_m) / 14.0) + 1.0)
    I_f = xf * (g_f * (-E_f + V_m))
    J_c_b = Vc * (bc * (-k_off_c) + cc * (k_on_c * (B_tot_c - bc)))
    df_Ca_dt = cd * (1.7 * (1.0 - f_Ca)) + (-0.012) * f_Ca
    values[0] = df_Ca_dt
    J_d_b = Vd * (bd * (-k_off_d) + cd * (k_on_d * (B_tot_d - bd)))
    J_d_c = alpha_d_c * (-cc + cd)
    J_leak = (alpha_RyR * gamma_RyR) * (cs - csl)
    J_n_s = alpha_n_s * (cn - cs)
    J_s_b = Vs * (bs * (-k_off_s) + cs * (k_on_s * (B_tot_s - bs)))
    J_sl_b = Vsl * (bsl * (-k_off_sl) + csl * (k_on_sl * (B_tot_sl - bsl)))
    J_sl_c = alpha_sl_c * (-cc + csl)
    Ka_sl = 1.0 / ((Kdact * Kdact) / (csl * csl) + 1.0)
    Xr2_infinity = numpy.where(
        SQT1,
        1.0 / (1.22986630710151 * numpy.exp(0.0258631837579206 * V_m) + 1.0),
        1.0 / (28.4822844754635 * numpy.exp(0.0478468899521531 * V_m) + 1.0),
    )
    sigma = numpy.exp(Nao / 67.0) / 7.0 + (-1.0) / 7.0
    i_Stim = numpy.where((V_m < -40.0), 1.0, 0.0) * numpy.where(
        numpy.logical_and(
            (stim_start <= -stim_period * numpy.floor(t / stim_period) + t),
            (stim_duration + stim_start >= -stim_period * numpy.floor(t / stim_period) + t),
        ),
        -stim_amplitude,
        0.0,
    )
    p = 1.0 / ((K_RyR * (K_RyR * K_RyR)) / (cd * (cd * cd)) + 1.0)
    s3_sl = csl * ((KmNao * (KmNao * KmNao)) * (1.0 + csl / KmCai)) + (
        (KmCai * (Nao * (Nao * Nao))) * ((Na_i * (Na_i * Na_i)) / (KmNai * (KmNai * KmNai)) + 1.0)
        + (
            csl * (Nao * (Nao * Nao))
            + (KmCao * (Na_i * (Na_i * Na_i)) + ce * (Na_i * (Na_i * Na_i)))
        )
    )
    eca_sl = numpy.log(ce / csl) / (2.0 * FoRT)
    ecl = numpy.log(Cli / Clo) / FoRT
    ek = numpy.log(Ko / K_i) / FoRT
    eks = numpy.log((Ko + Nao * pNaK) / (K_i + Na_i * pNaK)) / FoRT
    ena = numpy.log(Nao / Na_i) / FoRT
    ibarca_j = numpy.where(
        (numpy.abs(V_m) < 0.019306977288832503),
        5.551115123125783e-17 * FoRT**3 * Frdy * V_m**3 * cd * g_CaL
        + 0.2266666666666667 * FoRT**2 * Frdy * V_m**2 * cd * g_CaL
        - 0.2266666666666667 * FoRT**2 * Frdy * V_m**2 * ce * g_CaL
        + 0.68 * FoRT * Frdy * V_m * cd * g_CaL
        + 0.68 * FoRT * Frdy * V_m * ce * g_CaL
        + 0.68 * Frdy * cd * g_CaL
        - 0.68 * Frdy * ce * g_CaL,
        (
            V_m
            * (
                FoRT
                * (
                    ((4.0 * Frdy) * g_CaL)
                    * ((0.34 * cd) * numpy.exp((2.0 * FoRT) * V_m) + (-0.34) * ce)
                )
            )
        )
        / (numpy.exp((2.0 * FoRT) * V_m) - 1.0),
    )
    s1_sl = (ce * (Na_i * (Na_i * Na_i))) * numpy.exp(V_m * (FoRT * nu))
    s2_sl = (csl * (Nao * (Nao * Nao))) * numpy.exp(V_m * (FoRT * (nu - 1.0)))
    I_pCa = ((Q10pCa**Qpow * g_pCa) * (csl * csl)) / (KmPCa * KmPCa + csl * csl)
    J_SERCA = (
        (J_SERCA_bar * Q10SERCA**Qpow) * ((cc * cc) / (K_c * K_c) - (cn * cn) / (K_n * K_n))
    ) / ((cn * cn) / (K_n * K_n) + ((cc * cc) / (K_c * K_c) + 1.0))
    tau_q = Q10to ** (-Qpow) * (
        6.0
        + 39.0
        / (6.4664805167257 * numpy.exp(0.1 * V_m) + 0.0168716780456984 * numpy.exp((-0.08) * V_m))
    )
    tau_r = Q10to ** (-Qpow) * (
        2.75
        + 14.4
        / (15.7194688773159 * numpy.exp(0.09 * V_m) + 0.0207698622486295 * numpy.exp((-0.12) * V_m))
    )
    tau_xf = (1900.0 * Q10f ** (-Qpow)) / (4.48168907033806 * numpy.exp(0.1 * V_m) + 1.0)
    taum = Q10Na ** (-Qpow) * (
        0.06 * numpy.exp(-(V_m / 51.0 + (-5.0) / 51.0) * (V_m / 51.0 + (-5.0) / 51.0))
        + 0.13 * numpy.exp(-(V_m / 16.0 + 23.0 / 8.0) * (V_m / 16.0 + 23.0 / 8.0))
    )
    tauxs = (990.0 * Q10Ks ** (-Qpow)) / (0.842460441616771 * numpy.exp((-V_m) / 14.0) + 1.0)
    thLc = Q10NaL ** (-Qpow) * thL
    tau_Xr1 = beta_Xr1 * ((1.0 * Q10Kr_act ** (-Qpow)) * alpha_Xr1)
    tau_Xr2 = beta_Xr2 * ((1.0 * Q10Kr_inact ** (-Qpow)) * alpha_Xr2)
    tauj = Q10Na ** (-Qpow) / (aj + bj)
    taud = (dss * (1.0 - 0.434598208507078 * numpy.exp((-0.166666666666667) * V_m))) / (
        0.035 * V_m + 0.175
    )
    df_dt = (-f + fss) / tauf
    values[1] = df_dt
    tmL = Q10NaL ** (-Qpow) * tm
    dbc_dt = (1.0 * J_c_b) / Vc
    values[2] = dbc_dt
    dbd_dt = (1.0 * J_d_b) / Vd
    values[3] = dbd_dt
    dbs_dt = (1.0 * J_s_b) / Vs
    values[4] = dbs_dt
    dbsl_dt = (1.0 * J_sl_b) / Vsl
    values[5] = dbsl_dt
    fNaK = 1.0 / (
        sigma * (0.037 * numpy.exp((-FoRT) * V_m)) + (0.12 * numpy.exp(V_m * ((-0.1) * FoRT)) + 1.0)
    )
    J_RyR_active = r_RyR * (p * (alpha_RyR * (cs - csl)))
    I_bCa = g_bCa * (V_m - eca_sl)
    I_bCl = g_bCl * (V_m - ecl)
    I_Kr = Xr2 * (Xr1 * ((numpy.sqrt(Ko) * (0.430331482911935 * g_Kr)) * (V_m - ek)))
    I_to = r * (q * (g_to * (V_m - ek)))
    aK1 = 1.0 / (7.50455791507686e-06 * numpy.exp(0.2 * V_m - 0.2 * ek) + 1.0)
    bK1 = (
        3.32464030033236e-16 * numpy.exp(0.06 * V_m - 0.06 * ek)
        + 0.745912348820635 * numpy.exp(0.08 * V_m - 0.08 * ek)
    ) / (0.0820849986238988 * numpy.exp(-0.5 * V_m + 0.5 * ek) + 1.0)
    I_Ks = (g_Ks * (x_Ks * x_Ks)) * (V_m - eks)
    I_Na = j * ((g_Na * (m * (m * m))) * (V_m - ena))
    I_NaL = mL * (hL * (GNaL * (V_m - ena)))
    I_CaL = ibarca_j * (f * (d * (Q10CaL**Qpow * (1.0 - f_Ca))))
    I_NaCa = (Ka_sl * ((Q10NaCa**Qpow * g_NaCa) * (s1_sl - s2_sl))) / (
        s3_sl * (ksat * numpy.exp(V_m * (FoRT * (nu - 1.0))) + 1.0)
    )
    J_pCa = (I_pCa * ((-Cm) * chi)) / (2.0 * Frdy)
    dcc_dt = (1.0 * (J_sl_c + (J_d_c + (-J_SERCA - J_c_b)))) / Vc
    values[6] = dcc_dt
    dcn_dt = (1.0 * (J_SERCA - J_n_s)) / Vn
    values[7] = dcn_dt
    dq_dt = (-q + q_inf) / tau_q
    values[8] = dq_dt
    dr_dt = (-r + r_inf) / tau_r
    values[9] = dr_dt
    dxf_dt = (-xf + xf_inf) / tau_xf
    values[10] = dxf_dt
    dm_dt = (-m + mss) / taum
    values[11] = dm_dt
    dx_Ks_dt = (-x_Ks + xsss) / tauxs
    values[12] = dx_Ks_dt
    dhL_dt = (-hL + hLss) / thLc
    values[13] = dhL_dt
    dXr1_dt = (-Xr1 + Xr1_inf) / tau_Xr1
    values[14] = dXr1_dt
    dXr2_dt = (-Xr2 + Xr2_infinity) / tau_Xr2
    values[15] = dXr2_dt
    dj_dt = (-j + jss) / tauj
    values[16] = dj_dt
    dd_dt = (-d + dss) / taud
    values[17] = dd_dt
    dmL_dt = (-mL + mLss) / tmL
    values[18] = dmL_dt
    I_NaK = (fNaK * (Q10NaK**Qpow * (Ko * g_NaK))) / (
        (1.0 + (KmNaip**4.0 * Q10K_Nai ** (4.0 * Qpow)) / Na_i**4.0) * (KmKo + Ko)
    )
    J_RyR = J_RyR_active + J_leak
    dr_RyR_dt = (-J_RyR_active) / beta_RyR + (eta_RyR * (1.0 - r_RyR)) / p
    values[19] = dr_RyR_dt
    J_bCa = (I_bCa * ((-Cm) * chi)) / (2.0 * Frdy)
    K1ss = aK1 / (aK1 + bK1)
    J_CaL = (I_CaL * ((-Cm) * chi)) / (2.0 * Frdy)
    J_NaCa = (I_NaCa * (Cm * chi)) / Frdy
    I_Na_tot = I_NaL + (I_Na + (0.3293 * I_f + (3.0 * I_NaCa + 3.0 * I_NaK)))
    dcs_dt = (1.0 * (J_n_s + (-J_RyR - J_s_b))) / Vs
    values[20] = dcs_dt
    I_K1 = K1ss * ((numpy.sqrt(Ko) * (0.430331482911935 * g_K1)) * (V_m - ek))
    dcd_dt = (1.0 * (J_CaL + (-J_d_b - J_d_c))) / Vd
    values[21] = dcd_dt
    J_e_sl = J_pCa + (J_NaCa + J_bCa)
    J_Na = (I_Na_tot * ((-Cm) * chi)) / Frdy
    I_tot = I_to + (
        I_pCa
        + (
            I_f
            + (
                I_bCl
                + (I_bCa + (I_NaL + (I_NaK + (I_NaCa + (I_Na + (I_Ks + (I_Kr + (I_CaL + I_K1))))))))
            )
        )
    )
    dcsl_dt = (1.0 * (J_e_sl + (J_RyR + (-J_sl_b - J_sl_c)))) / Vsl
    values[22] = dcsl_dt
    dNa_i_dt = J_Na
    values[23] = dNa_i_dt
    dV_m_dt = -I_tot - i_Stim
    values[24] = dV_m_dt

    return values


def monitor_values(t, states, parameters):

    # Assign states
    f_Ca = states[0]
    f = states[1]
    bc = states[2]
    bd = states[3]
    bs = states[4]
    bsl = states[5]
    cc = states[6]
    cn = states[7]
    q = states[8]
    r = states[9]
    xf = states[10]
    m = states[11]
    x_Ks = states[12]
    hL = states[13]
    Xr1 = states[14]
    Xr2 = states[15]
    j = states[16]
    d = states[17]
    mL = states[18]
    r_RyR = states[19]
    cs = states[20]
    cd = states[21]
    csl = states[22]
    Na_i = states[23]
    V_m = states[24]

    # Assign parameters
    B_tot_c = parameters[0]
    B_tot_d = parameters[1]
    B_tot_s = parameters[2]
    B_tot_sl = parameters[3]
    Cli = parameters[4]
    Clo = parameters[5]
    Cm = parameters[6]
    E_f = parameters[7]
    Frdy = parameters[8]
    J_SERCA_bar = parameters[9]
    K_RyR = parameters[10]
    K_c = parameters[11]
    K_i = parameters[12]
    K_n = parameters[13]
    Kdact = parameters[14]
    KmCai = parameters[15]
    KmCao = parameters[16]
    KmKo = parameters[17]
    KmNai = parameters[18]
    KmNaip = parameters[19]
    KmNao = parameters[20]
    KmPCa = parameters[21]
    Ko = parameters[22]
    Nao = parameters[23]
    Q10CaL = parameters[24]
    Q10K_Nai = parameters[25]
    Q10Kr_act = parameters[26]
    Q10Kr_inact = parameters[27]
    Q10Ks = parameters[28]
    Q10Na = parameters[29]
    Q10NaCa = parameters[30]
    Q10NaK = parameters[31]
    Q10NaL = parameters[32]
    Q10SERCA = parameters[33]
    Q10f = parameters[34]
    Q10pCa = parameters[35]
    Q10to = parameters[36]
    R = parameters[37]
    SQT1 = parameters[38]
    Temp = parameters[39]
    Vc = parameters[40]
    Vd = parameters[41]
    Vn = parameters[42]
    Vs = parameters[43]
    Vsl = parameters[44]
    alpha_RyR = parameters[45]
    alpha_d_c = parameters[46]
    alpha_n_s = parameters[47]
    alpha_sl_c = parameters[48]
    beta_RyR = parameters[49]
    ce = parameters[50]
    chi = parameters[51]
    eta_RyR = parameters[52]
    g_CaL = parameters[53]
    g_K1 = parameters[54]
    g_Kr = parameters[55]
    g_Ks = parameters[56]
    g_Na = parameters[57]
    g_NaCa = parameters[58]
    g_NaK = parameters[59]
    g_NaL = parameters[60]
    g_bCa = parameters[61]
    g_bCl = parameters[62]
    g_f = parameters[63]
    g_pCa = parameters[64]
    g_to = parameters[65]
    gamma_RyR = parameters[66]
    k_off_c = parameters[67]
    k_off_d = parameters[68]
    k_off_s = parameters[69]
    k_off_sl = parameters[70]
    k_on_c = parameters[71]
    k_on_d = parameters[72]
    k_on_s = parameters[73]
    k_on_sl = parameters[74]
    ksat = parameters[75]
    nu = parameters[76]
    pNaK = parameters[77]
    stim_amplitude = parameters[78]
    stim_duration = parameters[79]
    stim_period = parameters[80]
    stim_start = parameters[81]
    thL = parameters[82]

    # Assign expressions
    shape = 108 if len(states.shape) == 1 else (108, states.shape[1])
    values = numpy.zeros(shape)
    FoRT = Frdy / (R * Temp)
    values[0] = FoRT
    Qpow = 0.1 * Temp - 31.0
    values[1] = Qpow
    GNaL = g_NaL
    values[2] = GNaL
    Xr1_inf = 1.0 / (1.19299933802777 * numpy.exp((-0.065359477124183) * V_m) + 1.0)
    values[3] = Xr1_inf
    aj = numpy.where(
        (V_m >= -40.0),
        0.0,
        ((V_m + 38.0) * ((-25000.0) * numpy.exp(0.2 * V_m) - 7e-06 * numpy.exp((-0.04) * V_m)))
        / (19623624323.6513 * numpy.exp(0.3 * V_m) + 1.0),
    )
    values[4] = aj
    alpha_Xr1 = 450.0 / (0.0111089965382423 * numpy.exp((-0.1) * V_m) + 1.0)
    values[5] = alpha_Xr1
    alpha_Xr2 = 3.0 / (0.0497870683678639 * numpy.exp((-0.05) * V_m) + 1.0)
    values[6] = alpha_Xr2
    beta_Xr1 = 6.0 / (13.5813245225782 * numpy.exp(0.0869565217391304 * V_m) + 1.0)
    values[7] = beta_Xr1
    beta_Xr2 = 1.12 / (0.0497870683678639 * numpy.exp(0.05 * V_m) + 1.0)
    values[8] = beta_Xr2
    bj = numpy.where(
        (V_m >= -40.0),
        (0.6 * numpy.exp(0.09 * V_m)) / (numpy.exp(-V_m - 40.0) + 1.0),
        (0.02 * numpy.exp((-0.01) * V_m)) / (0.00369786371648293 * numpy.exp((-0.14) * V_m) + 1.0),
    )
    values[9] = bj
    dss = 1.0 / (0.434598208507078 * numpy.exp((-0.166666666666667) * V_m) + 1.0)
    values[10] = dss
    fss = 0.6 / (12.1824939607035 * numpy.exp((-0.05) * V_m) + 1.0) + 1.0 / (
        48.8565712749872 * numpy.exp(0.111111111111111 * V_m) + 1.0
    )
    values[11] = fss
    hLss = 1.0 / (124658.506952443 * numpy.exp(0.133333333333333 * V_m) + 1.0)
    values[12] = hLss
    jss = 1.0 / (
        (numpy.exp(V_m / 7.0 + 72.0 / 7.0) + 1.0) * (numpy.exp(V_m / 7.0 + 72.0 / 7.0) + 1.0)
    )
    values[13] = jss
    mLss = 1.0 / (numpy.exp(-V_m / 5.0 + (-43.0) / 5.0) + 1.0)
    values[14] = mLss
    mss = 1.0 / (
        (numpy.exp(-V_m / 9.0 + (-19.0) / 3.0) + 1.0)
        * (numpy.exp(-V_m / 9.0 + (-19.0) / 3.0) + 1.0)
    )
    values[15] = mss
    q_inf = 1.0 / (58.9637634804245 * numpy.exp(0.0769230769230769 * V_m) + 1.0)
    values[16] = q_inf
    r_inf = 1.0 / (3.28489055021172 * numpy.exp((-0.0533333333333333) * V_m) + 1.0)
    values[17] = r_inf
    tauf = 1.0 / (0.02 + 0.02 * numpy.exp(-(0.034 * V_m + 0.493) * (0.034 * V_m + 0.493)))
    values[18] = tauf
    tm = 1.0 / (
        6.8 * numpy.exp(V_m / 35.0 + 12.0 / 35.0) + 8.6 * numpy.exp(-V_m / 6.0 + (-77.0) / 6.0)
    )
    values[19] = tm
    xf_inf = 1.0 / (5956538.01318462 * numpy.exp(0.2 * V_m) + 1.0)
    values[20] = xf_inf
    xsss = 1.0 / (0.762289730789954 * numpy.exp((-V_m) / 14.0) + 1.0)
    values[21] = xsss
    I_f = xf * (g_f * (-E_f + V_m))
    values[22] = I_f
    J_c_b = Vc * (bc * (-k_off_c) + cc * (k_on_c * (B_tot_c - bc)))
    values[23] = J_c_b
    df_Ca_dt = cd * (1.7 * (1.0 - f_Ca)) + (-0.012) * f_Ca
    values[24] = df_Ca_dt
    J_d_b = Vd * (bd * (-k_off_d) + cd * (k_on_d * (B_tot_d - bd)))
    values[25] = J_d_b
    J_d_c = alpha_d_c * (-cc + cd)
    values[26] = J_d_c
    J_leak = (alpha_RyR * gamma_RyR) * (cs - csl)
    values[27] = J_leak
    J_n_s = alpha_n_s * (cn - cs)
    values[28] = J_n_s
    J_s_b = Vs * (bs * (-k_off_s) + cs * (k_on_s * (B_tot_s - bs)))
    values[29] = J_s_b
    J_sl_b = Vsl * (bsl * (-k_off_sl) + csl * (k_on_sl * (B_tot_sl - bsl)))
    values[30] = J_sl_b
    J_sl_c = alpha_sl_c * (-cc + csl)
    values[31] = J_sl_c
    Ka_sl = 1.0 / ((Kdact * Kdact) / (csl * csl) + 1.0)
    values[32] = Ka_sl
    Xr2_infinity = numpy.where(
        SQT1,
        1.0 / (1.22986630710151 * numpy.exp(0.0258631837579206 * V_m) + 1.0),
        1.0 / (28.4822844754635 * numpy.exp(0.0478468899521531 * V_m) + 1.0),
    )
    values[33] = Xr2_infinity
    sigma = numpy.exp(Nao / 67.0) / 7.0 + (-1.0) / 7.0
    values[34] = sigma
    i_Stim = numpy.where((V_m < -40.0), 1.0, 0.0) * numpy.where(
        numpy.logical_and(
            (stim_start <= -stim_period * numpy.floor(t / stim_period) + t),
            (stim_duration + stim_start >= -stim_period * numpy.floor(t / stim_period) + t),
        ),
        -stim_amplitude,
        0.0,
    )
    values[35] = i_Stim
    p = 1.0 / ((K_RyR * (K_RyR * K_RyR)) / (cd * (cd * cd)) + 1.0)
    values[36] = p
    s3_sl = csl * ((KmNao * (KmNao * KmNao)) * (1.0 + csl / KmCai)) + (
        (KmCai * (Nao * (Nao * Nao))) * ((Na_i * (Na_i * Na_i)) / (KmNai * (KmNai * KmNai)) + 1.0)
        + (
            csl * (Nao * (Nao * Nao))
            + (KmCao * (Na_i * (Na_i * Na_i)) + ce * (Na_i * (Na_i * Na_i)))
        )
    )
    values[37] = s3_sl
    eca_sl = numpy.log(ce / csl) / (2.0 * FoRT)
    values[38] = eca_sl
    ecl = numpy.log(Cli / Clo) / FoRT
    values[39] = ecl
    ek = numpy.log(Ko / K_i) / FoRT
    values[40] = ek
    eks = numpy.log((Ko + Nao * pNaK) / (K_i + Na_i * pNaK)) / FoRT
    values[41] = eks
    ena = numpy.log(Nao / Na_i) / FoRT
    values[42] = ena
    ibarca_j = numpy.where(
        (numpy.abs(V_m) < 0.019306977288832503),
        5.551115123125783e-17 * FoRT**3 * Frdy * V_m**3 * cd * g_CaL
        + 0.2266666666666667 * FoRT**2 * Frdy * V_m**2 * cd * g_CaL
        - 0.2266666666666667 * FoRT**2 * Frdy * V_m**2 * ce * g_CaL
        + 0.68 * FoRT * Frdy * V_m * cd * g_CaL
        + 0.68 * FoRT * Frdy * V_m * ce * g_CaL
        + 0.68 * Frdy * cd * g_CaL
        - 0.68 * Frdy * ce * g_CaL,
        (
            V_m
            * (
                FoRT
                * (
                    ((4.0 * Frdy) * g_CaL)
                    * ((0.34 * cd) * numpy.exp((2.0 * FoRT) * V_m) + (-0.34) * ce)
                )
            )
        )
        / (numpy.exp((2.0 * FoRT) * V_m) - 1.0),
    )
    values[43] = ibarca_j
    s1_sl = (ce * (Na_i * (Na_i * Na_i))) * numpy.exp(V_m * (FoRT * nu))
    values[44] = s1_sl
    s2_sl = (csl * (Nao * (Nao * Nao))) * numpy.exp(V_m * (FoRT * (nu - 1.0)))
    values[45] = s2_sl
    I_pCa = ((Q10pCa**Qpow * g_pCa) * (csl * csl)) / (KmPCa * KmPCa + csl * csl)
    values[46] = I_pCa
    J_SERCA = (
        (J_SERCA_bar * Q10SERCA**Qpow) * ((cc * cc) / (K_c * K_c) - (cn * cn) / (K_n * K_n))
    ) / ((cn * cn) / (K_n * K_n) + ((cc * cc) / (K_c * K_c) + 1.0))
    values[47] = J_SERCA
    tau_q = Q10to ** (-Qpow) * (
        6.0
        + 39.0
        / (6.4664805167257 * numpy.exp(0.1 * V_m) + 0.0168716780456984 * numpy.exp((-0.08) * V_m))
    )
    values[48] = tau_q
    tau_r = Q10to ** (-Qpow) * (
        2.75
        + 14.4
        / (15.7194688773159 * numpy.exp(0.09 * V_m) + 0.0207698622486295 * numpy.exp((-0.12) * V_m))
    )
    values[49] = tau_r
    tau_xf = (1900.0 * Q10f ** (-Qpow)) / (4.48168907033806 * numpy.exp(0.1 * V_m) + 1.0)
    values[50] = tau_xf
    taum = Q10Na ** (-Qpow) * (
        0.06 * numpy.exp(-(V_m / 51.0 + (-5.0) / 51.0) * (V_m / 51.0 + (-5.0) / 51.0))
        + 0.13 * numpy.exp(-(V_m / 16.0 + 23.0 / 8.0) * (V_m / 16.0 + 23.0 / 8.0))
    )
    values[51] = taum
    tauxs = (990.0 * Q10Ks ** (-Qpow)) / (0.842460441616771 * numpy.exp((-V_m) / 14.0) + 1.0)
    values[52] = tauxs
    thLc = Q10NaL ** (-Qpow) * thL
    values[53] = thLc
    tau_Xr1 = beta_Xr1 * ((1.0 * Q10Kr_act ** (-Qpow)) * alpha_Xr1)
    values[54] = tau_Xr1
    tau_Xr2 = beta_Xr2 * ((1.0 * Q10Kr_inact ** (-Qpow)) * alpha_Xr2)
    values[55] = tau_Xr2
    tauj = Q10Na ** (-Qpow) / (aj + bj)
    values[56] = tauj
    taud = (dss * (1.0 - 0.434598208507078 * numpy.exp((-0.166666666666667) * V_m))) / (
        0.035 * V_m + 0.175
    )
    values[57] = taud
    df_dt = (-f + fss) / tauf
    values[58] = df_dt
    tmL = Q10NaL ** (-Qpow) * tm
    values[59] = tmL
    dbc_dt = (1.0 * J_c_b) / Vc
    values[60] = dbc_dt
    dbd_dt = (1.0 * J_d_b) / Vd
    values[61] = dbd_dt
    dbs_dt = (1.0 * J_s_b) / Vs
    values[62] = dbs_dt
    dbsl_dt = (1.0 * J_sl_b) / Vsl
    values[63] = dbsl_dt
    fNaK = 1.0 / (
        sigma * (0.037 * numpy.exp((-FoRT) * V_m)) + (0.12 * numpy.exp(V_m * ((-0.1) * FoRT)) + 1.0)
    )
    values[64] = fNaK
    J_RyR_active = r_RyR * (p * (alpha_RyR * (cs - csl)))
    values[65] = J_RyR_active
    I_bCa = g_bCa * (V_m - eca_sl)
    values[66] = I_bCa
    I_bCl = g_bCl * (V_m - ecl)
    values[67] = I_bCl
    I_Kr = Xr2 * (Xr1 * ((numpy.sqrt(Ko) * (0.430331482911935 * g_Kr)) * (V_m - ek)))
    values[68] = I_Kr
    I_to = r * (q * (g_to * (V_m - ek)))
    values[69] = I_to
    aK1 = 1.0 / (7.50455791507686e-06 * numpy.exp(0.2 * V_m - 0.2 * ek) + 1.0)
    values[70] = aK1
    bK1 = (
        3.32464030033236e-16 * numpy.exp(0.06 * V_m - 0.06 * ek)
        + 0.745912348820635 * numpy.exp(0.08 * V_m - 0.08 * ek)
    ) / (0.0820849986238988 * numpy.exp(-0.5 * V_m + 0.5 * ek) + 1.0)
    values[71] = bK1
    I_Ks = (g_Ks * (x_Ks * x_Ks)) * (V_m - eks)
    values[72] = I_Ks
    I_Na = j * ((g_Na * (m * (m * m))) * (V_m - ena))
    values[73] = I_Na
    I_NaL = mL * (hL * (GNaL * (V_m - ena)))
    values[74] = I_NaL
    I_CaL = ibarca_j * (f * (d * (Q10CaL**Qpow * (1.0 - f_Ca))))
    values[75] = I_CaL
    I_NaCa = (Ka_sl * ((Q10NaCa**Qpow * g_NaCa) * (s1_sl - s2_sl))) / (
        s3_sl * (ksat * numpy.exp(V_m * (FoRT * (nu - 1.0))) + 1.0)
    )
    values[76] = I_NaCa
    J_pCa = (I_pCa * ((-Cm) * chi)) / (2.0 * Frdy)
    values[77] = J_pCa
    dcc_dt = (1.0 * (J_sl_c + (J_d_c + (-J_SERCA - J_c_b)))) / Vc
    values[78] = dcc_dt
    dcn_dt = (1.0 * (J_SERCA - J_n_s)) / Vn
    values[79] = dcn_dt
    dq_dt = (-q + q_inf) / tau_q
    values[80] = dq_dt
    dr_dt = (-r + r_inf) / tau_r
    values[81] = dr_dt
    dxf_dt = (-xf + xf_inf) / tau_xf
    values[82] = dxf_dt
    dm_dt = (-m + mss) / taum
    values[83] = dm_dt
    dx_Ks_dt = (-x_Ks + xsss) / tauxs
    values[84] = dx_Ks_dt
    dhL_dt = (-hL + hLss) / thLc
    values[85] = dhL_dt
    dXr1_dt = (-Xr1 + Xr1_inf) / tau_Xr1
    values[86] = dXr1_dt
    dXr2_dt = (-Xr2 + Xr2_infinity) / tau_Xr2
    values[87] = dXr2_dt
    dj_dt = (-j + jss) / tauj
    values[88] = dj_dt
    dd_dt = (-d + dss) / taud
    values[89] = dd_dt
    dmL_dt = (-mL + mLss) / tmL
    values[90] = dmL_dt
    I_NaK = (fNaK * (Q10NaK**Qpow * (Ko * g_NaK))) / (
        (1.0 + (KmNaip**4.0 * Q10K_Nai ** (4.0 * Qpow)) / Na_i**4.0) * (KmKo + Ko)
    )
    values[91] = I_NaK
    J_RyR = J_RyR_active + J_leak
    values[92] = J_RyR
    dr_RyR_dt = (-J_RyR_active) / beta_RyR + (eta_RyR * (1.0 - r_RyR)) / p
    values[93] = dr_RyR_dt
    J_bCa = (I_bCa * ((-Cm) * chi)) / (2.0 * Frdy)
    values[94] = J_bCa
    K1ss = aK1 / (aK1 + bK1)
    values[95] = K1ss
    J_CaL = (I_CaL * ((-Cm) * chi)) / (2.0 * Frdy)
    values[96] = J_CaL
    J_NaCa = (I_NaCa * (Cm * chi)) / Frdy
    values[97] = J_NaCa
    I_Na_tot = I_NaL + (I_Na + (0.3293 * I_f + (3.0 * I_NaCa + 3.0 * I_NaK)))
    values[98] = I_Na_tot
    dcs_dt = (1.0 * (J_n_s + (-J_RyR - J_s_b))) / Vs
    values[99] = dcs_dt
    I_K1 = K1ss * ((numpy.sqrt(Ko) * (0.430331482911935 * g_K1)) * (V_m - ek))
    values[100] = I_K1
    dcd_dt = (1.0 * (J_CaL + (-J_d_b - J_d_c))) / Vd
    values[101] = dcd_dt
    J_e_sl = J_pCa + (J_NaCa + J_bCa)
    values[102] = J_e_sl
    J_Na = (I_Na_tot * ((-Cm) * chi)) / Frdy
    values[103] = J_Na
    I_tot = I_to + (
        I_pCa
        + (
            I_f
            + (
                I_bCl
                + (I_bCa + (I_NaL + (I_NaK + (I_NaCa + (I_Na + (I_Ks + (I_Kr + (I_CaL + I_K1))))))))
            )
        )
    )
    values[104] = I_tot
    dcsl_dt = (1.0 * (J_e_sl + (J_RyR + (-J_sl_b - J_sl_c)))) / Vsl
    values[105] = dcsl_dt
    dNa_i_dt = J_Na
    values[106] = dNa_i_dt
    dV_m_dt = -I_tot - i_Stim
    values[107] = dV_m_dt

    return values


def generalized_rush_larsen(states, t, dt, parameters):

    # Assign states
    f_Ca = states[0]
    f = states[1]
    bc = states[2]
    bd = states[3]
    bs = states[4]
    bsl = states[5]
    cc = states[6]
    cn = states[7]
    q = states[8]
    r = states[9]
    xf = states[10]
    m = states[11]
    x_Ks = states[12]
    hL = states[13]
    Xr1 = states[14]
    Xr2 = states[15]
    j = states[16]
    d = states[17]
    mL = states[18]
    r_RyR = states[19]
    cs = states[20]
    cd = states[21]
    csl = states[22]
    Na_i = states[23]
    V_m = states[24]

    # Assign parameters
    B_tot_c = parameters[0]
    B_tot_d = parameters[1]
    B_tot_s = parameters[2]
    B_tot_sl = parameters[3]
    Cli = parameters[4]
    Clo = parameters[5]
    Cm = parameters[6]
    E_f = parameters[7]
    Frdy = parameters[8]
    J_SERCA_bar = parameters[9]
    K_RyR = parameters[10]
    K_c = parameters[11]
    K_i = parameters[12]
    K_n = parameters[13]
    Kdact = parameters[14]
    KmCai = parameters[15]
    KmCao = parameters[16]
    KmKo = parameters[17]
    KmNai = parameters[18]
    KmNaip = parameters[19]
    KmNao = parameters[20]
    KmPCa = parameters[21]
    Ko = parameters[22]
    Nao = parameters[23]
    Q10CaL = parameters[24]
    Q10K_Nai = parameters[25]
    Q10Kr_act = parameters[26]
    Q10Kr_inact = parameters[27]
    Q10Ks = parameters[28]
    Q10Na = parameters[29]
    Q10NaCa = parameters[30]
    Q10NaK = parameters[31]
    Q10NaL = parameters[32]
    Q10SERCA = parameters[33]
    Q10f = parameters[34]
    Q10pCa = parameters[35]
    Q10to = parameters[36]
    R = parameters[37]
    SQT1 = parameters[38]
    Temp = parameters[39]
    Vc = parameters[40]
    Vd = parameters[41]
    Vn = parameters[42]
    Vs = parameters[43]
    Vsl = parameters[44]
    alpha_RyR = parameters[45]
    alpha_d_c = parameters[46]
    alpha_n_s = parameters[47]
    alpha_sl_c = parameters[48]
    beta_RyR = parameters[49]
    ce = parameters[50]
    chi = parameters[51]
    eta_RyR = parameters[52]
    g_CaL = parameters[53]
    g_K1 = parameters[54]
    g_Kr = parameters[55]
    g_Ks = parameters[56]
    g_Na = parameters[57]
    g_NaCa = parameters[58]
    g_NaK = parameters[59]
    g_NaL = parameters[60]
    g_bCa = parameters[61]
    g_bCl = parameters[62]
    g_f = parameters[63]
    g_pCa = parameters[64]
    g_to = parameters[65]
    gamma_RyR = parameters[66]
    k_off_c = parameters[67]
    k_off_d = parameters[68]
    k_off_s = parameters[69]
    k_off_sl = parameters[70]
    k_on_c = parameters[71]
    k_on_d = parameters[72]
    k_on_s = parameters[73]
    k_on_sl = parameters[74]
    ksat = parameters[75]
    nu = parameters[76]
    pNaK = parameters[77]
    stim_amplitude = parameters[78]
    stim_duration = parameters[79]
    stim_period = parameters[80]
    stim_start = parameters[81]
    thL = parameters[82]

    # Assign expressions

    values = numpy.zeros_like(states, dtype=numpy.float64)
    FoRT = Frdy / (R * Temp)
    Qpow = 0.1 * Temp - 31.0
    GNaL = g_NaL
    Xr1_inf = 1.0 / (1.19299933802777 * numpy.exp((-0.065359477124183) * V_m) + 1.0)
    aj = numpy.where(
        (V_m >= -40.0),
        0.0,
        ((V_m + 38.0) * ((-25000.0) * numpy.exp(0.2 * V_m) - 7e-06 * numpy.exp((-0.04) * V_m)))
        / (19623624323.6513 * numpy.exp(0.3 * V_m) + 1.0),
    )
    alpha_Xr1 = 450.0 / (0.0111089965382423 * numpy.exp((-0.1) * V_m) + 1.0)
    alpha_Xr2 = 3.0 / (0.0497870683678639 * numpy.exp((-0.05) * V_m) + 1.0)
    beta_Xr1 = 6.0 / (13.5813245225782 * numpy.exp(0.0869565217391304 * V_m) + 1.0)
    beta_Xr2 = 1.12 / (0.0497870683678639 * numpy.exp(0.05 * V_m) + 1.0)
    bj = numpy.where(
        (V_m >= -40.0),
        (0.6 * numpy.exp(0.09 * V_m)) / (numpy.exp(-V_m - 40.0) + 1.0),
        (0.02 * numpy.exp((-0.01) * V_m)) / (0.00369786371648293 * numpy.exp((-0.14) * V_m) + 1.0),
    )
    dss = 1.0 / (0.434598208507078 * numpy.exp((-0.166666666666667) * V_m) + 1.0)
    fss = 0.6 / (12.1824939607035 * numpy.exp((-0.05) * V_m) + 1.0) + 1.0 / (
        48.8565712749872 * numpy.exp(0.111111111111111 * V_m) + 1.0
    )
    hLss = 1.0 / (124658.506952443 * numpy.exp(0.133333333333333 * V_m) + 1.0)
    jss = 1.0 / (
        (numpy.exp(V_m / 7.0 + 72.0 / 7.0) + 1.0) * (numpy.exp(V_m / 7.0 + 72.0 / 7.0) + 1.0)
    )
    mLss = 1.0 / (numpy.exp(-V_m / 5.0 + (-43.0) / 5.0) + 1.0)
    mss = 1.0 / (
        (numpy.exp(-V_m / 9.0 + (-19.0) / 3.0) + 1.0)
        * (numpy.exp(-V_m / 9.0 + (-19.0) / 3.0) + 1.0)
    )
    q_inf = 1.0 / (58.9637634804245 * numpy.exp(0.0769230769230769 * V_m) + 1.0)
    r_inf = 1.0 / (3.28489055021172 * numpy.exp((-0.0533333333333333) * V_m) + 1.0)
    tauf = 1.0 / (0.02 + 0.02 * numpy.exp(-(0.034 * V_m + 0.493) * (0.034 * V_m + 0.493)))
    tm = 1.0 / (
        6.8 * numpy.exp(V_m / 35.0 + 12.0 / 35.0) + 8.6 * numpy.exp(-V_m / 6.0 + (-77.0) / 6.0)
    )
    xf_inf = 1.0 / (5956538.01318462 * numpy.exp(0.2 * V_m) + 1.0)
    xsss = 1.0 / (0.762289730789954 * numpy.exp((-V_m) / 14.0) + 1.0)
    I_f = xf * (g_f * (-E_f + V_m))
    J_c_b = Vc * (bc * (-k_off_c) + cc * (k_on_c * (B_tot_c - bc)))
    df_Ca_dt = cd * (1.7 * (1.0 - f_Ca)) + (-0.012) * f_Ca
    df_Ca_dt_linearized = -1.7 * cd - 0.012
    values[0] = f_Ca + numpy.where(
        numpy.logical_or((df_Ca_dt_linearized > 1e-08), (df_Ca_dt_linearized < -1e-08)),
        df_Ca_dt * (numpy.exp(df_Ca_dt_linearized * dt) - 1) / df_Ca_dt_linearized,
        df_Ca_dt * dt,
    )
    J_d_b = Vd * (bd * (-k_off_d) + cd * (k_on_d * (B_tot_d - bd)))
    J_d_c = alpha_d_c * (-cc + cd)
    J_leak = (alpha_RyR * gamma_RyR) * (cs - csl)
    J_n_s = alpha_n_s * (cn - cs)
    J_s_b = Vs * (bs * (-k_off_s) + cs * (k_on_s * (B_tot_s - bs)))
    J_sl_b = Vsl * (bsl * (-k_off_sl) + csl * (k_on_sl * (B_tot_sl - bsl)))
    J_sl_c = alpha_sl_c * (-cc + csl)
    Ka_sl = 1.0 / ((Kdact * Kdact) / (csl * csl) + 1.0)
    Xr2_infinity = numpy.where(
        SQT1,
        1.0 / (1.22986630710151 * numpy.exp(0.0258631837579206 * V_m) + 1.0),
        1.0 / (28.4822844754635 * numpy.exp(0.0478468899521531 * V_m) + 1.0),
    )
    sigma = numpy.exp(Nao / 67.0) / 7.0 + (-1.0) / 7.0
    i_Stim = numpy.where((V_m < -40.0), 1.0, 0.0) * numpy.where(
        numpy.logical_and(
            (stim_start <= -stim_period * numpy.floor(t / stim_period) + t),
            (stim_duration + stim_start >= -stim_period * numpy.floor(t / stim_period) + t),
        ),
        -stim_amplitude,
        0.0,
    )
    p = 1.0 / ((K_RyR * (K_RyR * K_RyR)) / (cd * (cd * cd)) + 1.0)
    s3_sl = csl * ((KmNao * (KmNao * KmNao)) * (1.0 + csl / KmCai)) + (
        (KmCai * (Nao * (Nao * Nao))) * ((Na_i * (Na_i * Na_i)) / (KmNai * (KmNai * KmNai)) + 1.0)
        + (
            csl * (Nao * (Nao * Nao))
            + (KmCao * (Na_i * (Na_i * Na_i)) + ce * (Na_i * (Na_i * Na_i)))
        )
    )
    eca_sl = numpy.log(ce / csl) / (2.0 * FoRT)
    ecl = numpy.log(Cli / Clo) / FoRT
    ek = numpy.log(Ko / K_i) / FoRT
    eks = numpy.log((Ko + Nao * pNaK) / (K_i + Na_i * pNaK)) / FoRT
    ena = numpy.log(Nao / Na_i) / FoRT
    ibarca_j = numpy.where(
        (numpy.abs(V_m) < 0.019306977288832503),
        5.551115123125783e-17 * FoRT**3 * Frdy * V_m**3 * cd * g_CaL
        + 0.2266666666666667 * FoRT**2 * Frdy * V_m**2 * cd * g_CaL
        - 0.2266666666666667 * FoRT**2 * Frdy * V_m**2 * ce * g_CaL
        + 0.68 * FoRT * Frdy * V_m * cd * g_CaL
        + 0.68 * FoRT * Frdy * V_m * ce * g_CaL
        + 0.68 * Frdy * cd * g_CaL
        - 0.68 * Frdy * ce * g_CaL,
        (
            V_m
            * (
                FoRT
                * (
                    ((4.0 * Frdy) * g_CaL)
                    * ((0.34 * cd) * numpy.exp((2.0 * FoRT) * V_m) + (-0.34) * ce)
                )
            )
        )
        / (numpy.exp((2.0 * FoRT) * V_m) - 1.0),
    )
    s1_sl = (ce * (Na_i * (Na_i * Na_i))) * numpy.exp(V_m * (FoRT * nu))
    s2_sl = (csl * (Nao * (Nao * Nao))) * numpy.exp(V_m * (FoRT * (nu - 1.0)))
    I_pCa = ((Q10pCa**Qpow * g_pCa) * (csl * csl)) / (KmPCa * KmPCa + csl * csl)
    J_SERCA = (
        (J_SERCA_bar * Q10SERCA**Qpow) * ((cc * cc) / (K_c * K_c) - (cn * cn) / (K_n * K_n))
    ) / ((cn * cn) / (K_n * K_n) + ((cc * cc) / (K_c * K_c) + 1.0))
    tau_q = Q10to ** (-Qpow) * (
        6.0
        + 39.0
        / (6.4664805167257 * numpy.exp(0.1 * V_m) + 0.0168716780456984 * numpy.exp((-0.08) * V_m))
    )
    tau_r = Q10to ** (-Qpow) * (
        2.75
        + 14.4
        / (15.7194688773159 * numpy.exp(0.09 * V_m) + 0.0207698622486295 * numpy.exp((-0.12) * V_m))
    )
    tau_xf = (1900.0 * Q10f ** (-Qpow)) / (4.48168907033806 * numpy.exp(0.1 * V_m) + 1.0)
    taum = Q10Na ** (-Qpow) * (
        0.06 * numpy.exp(-(V_m / 51.0 + (-5.0) / 51.0) * (V_m / 51.0 + (-5.0) / 51.0))
        + 0.13 * numpy.exp(-(V_m / 16.0 + 23.0 / 8.0) * (V_m / 16.0 + 23.0 / 8.0))
    )
    tauxs = (990.0 * Q10Ks ** (-Qpow)) / (0.842460441616771 * numpy.exp((-V_m) / 14.0) + 1.0)
    thLc = Q10NaL ** (-Qpow) * thL
    tau_Xr1 = beta_Xr1 * ((1.0 * Q10Kr_act ** (-Qpow)) * alpha_Xr1)
    tau_Xr2 = beta_Xr2 * ((1.0 * Q10Kr_inact ** (-Qpow)) * alpha_Xr2)
    tauj = Q10Na ** (-Qpow) / (aj + bj)
    taud = (dss * (1.0 - 0.434598208507078 * numpy.exp((-0.166666666666667) * V_m))) / (
        0.035 * V_m + 0.175
    )
    df_dt = (-f + fss) / tauf
    df_dt_linearized = -1 / tauf
    values[1] = df_dt * (numpy.exp(df_dt_linearized * dt) - 1) / df_dt_linearized + f
    tmL = Q10NaL ** (-Qpow) * tm
    dbc_dt = (1.0 * J_c_b) / Vc
    dbc_dt_linearized = -1.0 * (cc * k_on_c + k_off_c)
    values[2] = bc + numpy.where(
        numpy.logical_or((dbc_dt_linearized > 1e-08), (dbc_dt_linearized < -1e-08)),
        dbc_dt * (numpy.exp(dbc_dt_linearized * dt) - 1) / dbc_dt_linearized,
        dbc_dt * dt,
    )
    dbd_dt = (1.0 * J_d_b) / Vd
    dbd_dt_linearized = -1.0 * (cd * k_on_d + k_off_d)
    values[3] = bd + numpy.where(
        numpy.logical_or((dbd_dt_linearized > 1e-08), (dbd_dt_linearized < -1e-08)),
        dbd_dt * (numpy.exp(dbd_dt_linearized * dt) - 1) / dbd_dt_linearized,
        dbd_dt * dt,
    )
    dbs_dt = (1.0 * J_s_b) / Vs
    dbs_dt_linearized = -1.0 * (cs * k_on_s + k_off_s)
    values[4] = bs + numpy.where(
        numpy.logical_or((dbs_dt_linearized > 1e-08), (dbs_dt_linearized < -1e-08)),
        dbs_dt * (numpy.exp(dbs_dt_linearized * dt) - 1) / dbs_dt_linearized,
        dbs_dt * dt,
    )
    dbsl_dt = (1.0 * J_sl_b) / Vsl
    dbsl_dt_linearized = -1.0 * (csl * k_on_sl + k_off_sl)
    values[5] = bsl + numpy.where(
        numpy.logical_or((dbsl_dt_linearized > 1e-08), (dbsl_dt_linearized < -1e-08)),
        dbsl_dt * (numpy.exp(dbsl_dt_linearized * dt) - 1) / dbsl_dt_linearized,
        dbsl_dt * dt,
    )
    fNaK = 1.0 / (
        sigma * (0.037 * numpy.exp((-FoRT) * V_m)) + (0.12 * numpy.exp(V_m * ((-0.1) * FoRT)) + 1.0)
    )
    J_RyR_active = r_RyR * (p * (alpha_RyR * (cs - csl)))
    I_bCa = g_bCa * (V_m - eca_sl)
    I_bCl = g_bCl * (V_m - ecl)
    I_Kr = Xr2 * (Xr1 * ((numpy.sqrt(Ko) * (0.430331482911935 * g_Kr)) * (V_m - ek)))
    I_to = r * (q * (g_to * (V_m - ek)))
    aK1 = 1.0 / (7.50455791507686e-06 * numpy.exp(0.2 * V_m - 0.2 * ek) + 1.0)
    bK1 = (
        3.32464030033236e-16 * numpy.exp(0.06 * V_m - 0.06 * ek)
        + 0.745912348820635 * numpy.exp(0.08 * V_m - 0.08 * ek)
    ) / (0.0820849986238988 * numpy.exp(-0.5 * V_m + 0.5 * ek) + 1.0)
    I_Ks = (g_Ks * (x_Ks * x_Ks)) * (V_m - eks)
    I_Na = j * ((g_Na * (m * (m * m))) * (V_m - ena))
    I_NaL = mL * (hL * (GNaL * (V_m - ena)))
    I_CaL = ibarca_j * (f * (d * (Q10CaL**Qpow * (1.0 - f_Ca))))
    I_NaCa = (Ka_sl * ((Q10NaCa**Qpow * g_NaCa) * (s1_sl - s2_sl))) / (
        s3_sl * (ksat * numpy.exp(V_m * (FoRT * (nu - 1.0))) + 1.0)
    )
    J_pCa = (I_pCa * ((-Cm) * chi)) / (2.0 * Frdy)
    dcc_dt = (1.0 * (J_sl_c + (J_d_c + (-J_SERCA - J_c_b)))) / Vc
    _linearization_temp_0 = 1 / Vc
    _linearization_temp_1 = 1.0 * _linearization_temp_0
    _linearization_temp_2 = K_c ** (-2)
    _linearization_temp_3 = Q10SERCA**Qpow
    _linearization_temp_4 = cc**2
    _linearization_temp_5 = K_n ** (-2)
    _linearization_temp_6 = _linearization_temp_5 * cn**2
    _linearization_temp_7 = 1 / (
        _linearization_temp_2 * _linearization_temp_4 + _linearization_temp_6 + 1.0
    )
    _linearization_temp_8 = _linearization_temp_7 * (
        _linearization_temp_2 * _linearization_temp_4 - _linearization_temp_6
    )
    dcc_dt_linearized = (
        2.0
        * J_SERCA_bar
        * _linearization_temp_0
        * _linearization_temp_2
        * _linearization_temp_3
        * _linearization_temp_7
        * cc
        * (_linearization_temp_8 - 1)
        - _linearization_temp_1 * alpha_d_c
        - _linearization_temp_1 * alpha_sl_c
        - 1.0 * k_on_c * (B_tot_c - bc)
    )
    values[6] = cc + numpy.where(
        numpy.logical_or((dcc_dt_linearized > 1e-08), (dcc_dt_linearized < -1e-08)),
        dcc_dt * (numpy.exp(dcc_dt_linearized * dt) - 1) / dcc_dt_linearized,
        dcc_dt * dt,
    )
    dcn_dt = (1.0 * (J_SERCA - J_n_s)) / Vn
    dcn_dt_linearized = (
        -(
            2.0
            * J_SERCA_bar
            * _linearization_temp_3
            * _linearization_temp_5
            * _linearization_temp_7
            * cn
            * (_linearization_temp_8 + 1)
            + 1.0 * alpha_n_s
        )
        / Vn
    )
    values[7] = cn + numpy.where(
        numpy.logical_or((dcn_dt_linearized > 1e-08), (dcn_dt_linearized < -1e-08)),
        dcn_dt * (numpy.exp(dcn_dt_linearized * dt) - 1) / dcn_dt_linearized,
        dcn_dt * dt,
    )
    dq_dt = (-q + q_inf) / tau_q
    dq_dt_linearized = -1 / tau_q
    values[8] = dq_dt * (numpy.exp(dq_dt_linearized * dt) - 1) / dq_dt_linearized + q
    dr_dt = (-r + r_inf) / tau_r
    dr_dt_linearized = -1 / tau_r
    values[9] = dr_dt * (numpy.exp(dr_dt_linearized * dt) - 1) / dr_dt_linearized + r
    dxf_dt = (-xf + xf_inf) / tau_xf
    dxf_dt_linearized = -1 / tau_xf
    values[10] = dxf_dt * (numpy.exp(dt * dxf_dt_linearized) - 1) / dxf_dt_linearized + xf
    dm_dt = (-m + mss) / taum
    dm_dt_linearized = -1 / taum
    values[11] = dm_dt * (numpy.exp(dm_dt_linearized * dt) - 1) / dm_dt_linearized + m
    dx_Ks_dt = (-x_Ks + xsss) / tauxs
    dx_Ks_dt_linearized = -1 / tauxs
    values[12] = dx_Ks_dt * (numpy.exp(dt * dx_Ks_dt_linearized) - 1) / dx_Ks_dt_linearized + x_Ks
    dhL_dt = (-hL + hLss) / thLc
    dhL_dt_linearized = -1 / thLc
    values[13] = dhL_dt * (numpy.exp(dhL_dt_linearized * dt) - 1) / dhL_dt_linearized + hL
    dXr1_dt = (-Xr1 + Xr1_inf) / tau_Xr1
    dXr1_dt_linearized = -1 / tau_Xr1
    values[14] = Xr1 + dXr1_dt * (numpy.exp(dXr1_dt_linearized * dt) - 1) / dXr1_dt_linearized
    dXr2_dt = (-Xr2 + Xr2_infinity) / tau_Xr2
    dXr2_dt_linearized = -1 / tau_Xr2
    values[15] = Xr2 + dXr2_dt * (numpy.exp(dXr2_dt_linearized * dt) - 1) / dXr2_dt_linearized
    dj_dt = (-j + jss) / tauj
    dj_dt_linearized = -1 / tauj
    values[16] = dj_dt * (numpy.exp(dj_dt_linearized * dt) - 1) / dj_dt_linearized + j
    dd_dt = (-d + dss) / taud
    dd_dt_linearized = -1 / taud
    values[17] = d + dd_dt * (numpy.exp(dd_dt_linearized * dt) - 1) / dd_dt_linearized
    dmL_dt = (-mL + mLss) / tmL
    dmL_dt_linearized = -1 / tmL
    values[18] = dmL_dt * (numpy.exp(dmL_dt_linearized * dt) - 1) / dmL_dt_linearized + mL
    I_NaK = (fNaK * (Q10NaK**Qpow * (Ko * g_NaK))) / (
        (1.0 + (KmNaip**4.0 * Q10K_Nai ** (4.0 * Qpow)) / Na_i**4.0) * (KmKo + Ko)
    )
    J_RyR = J_RyR_active + J_leak
    dr_RyR_dt = (-J_RyR_active) / beta_RyR + (eta_RyR * (1.0 - r_RyR)) / p
    dr_RyR_dt_linearized = -alpha_RyR * p * (cs - csl) / beta_RyR - eta_RyR / p
    values[19] = r_RyR + numpy.where(
        numpy.logical_or((dr_RyR_dt_linearized > 1e-08), (dr_RyR_dt_linearized < -1e-08)),
        dr_RyR_dt * (numpy.exp(dr_RyR_dt_linearized * dt) - 1) / dr_RyR_dt_linearized,
        dr_RyR_dt * dt,
    )
    J_bCa = (I_bCa * ((-Cm) * chi)) / (2.0 * Frdy)
    K1ss = aK1 / (aK1 + bK1)
    J_CaL = (I_CaL * ((-Cm) * chi)) / (2.0 * Frdy)
    J_NaCa = (I_NaCa * (Cm * chi)) / Frdy
    I_Na_tot = I_NaL + (I_Na + (0.3293 * I_f + (3.0 * I_NaCa + 3.0 * I_NaK)))
    dcs_dt = (1.0 * (J_n_s + (-J_RyR - J_s_b))) / Vs
    _linearization_temp_9 = 1 / Vs
    _linearization_temp_10 = alpha_RyR * (gamma_RyR + p * r_RyR)
    dcs_dt_linearized = (
        -1.0 * _linearization_temp_10 * _linearization_temp_9
        - 1.0 * _linearization_temp_9 * alpha_n_s
        - 1.0 * k_on_s * (B_tot_s - bs)
    )
    values[20] = cs + numpy.where(
        numpy.logical_or((dcs_dt_linearized > 1e-08), (dcs_dt_linearized < -1e-08)),
        dcs_dt * (numpy.exp(dcs_dt_linearized * dt) - 1) / dcs_dt_linearized,
        dcs_dt * dt,
    )
    I_K1 = K1ss * ((numpy.sqrt(Ko) * (0.430331482911935 * g_K1)) * (V_m - ek))
    dcd_dt = (1.0 * (J_CaL + (-J_d_b - J_d_c))) / Vd
    _linearization_temp_11 = 1 / Vd
    _linearization_temp_12 = f_Ca - 1.0
    _linearization_temp_13 = 1 / Frdy
    _linearization_temp_14 = Q10CaL**Qpow
    dcd_dt_linearized = (
        0.5
        * Cm
        * _linearization_temp_11
        * _linearization_temp_12
        * _linearization_temp_13
        * _linearization_temp_14
        * chi
        * d
        * f
        * numpy.where(
            numpy.logical_and((V_m > -0.019306977288832503), (V_m < 0.019306977288832503)),
            Frdy
            * g_CaL
            * (
                5.551115123125783e-17 * FoRT**3 * V_m**3
                + 0.2266666666666667 * FoRT**2 * V_m**2
                + 0.68 * FoRT * V_m
                + 0.68
            ),
            1.36
            * FoRT
            * Frdy
            * V_m
            * g_CaL
            * numpy.exp(2.0 * FoRT * V_m)
            / (numpy.exp(2.0 * FoRT * V_m) - 1.0),
        )
        - 1.0 * _linearization_temp_11 * alpha_d_c
        - 1.0 * k_on_d * (B_tot_d - bd)
    )
    values[21] = cd + numpy.where(
        numpy.logical_or((dcd_dt_linearized > 1e-08), (dcd_dt_linearized < -1e-08)),
        dcd_dt * (numpy.exp(dcd_dt_linearized * dt) - 1) / dcd_dt_linearized,
        dcd_dt * dt,
    )
    J_e_sl = J_pCa + (J_NaCa + J_bCa)
    J_Na = (I_Na_tot * ((-Cm) * chi)) / Frdy
    I_tot = I_to + (
        I_pCa
        + (
            I_f
            + (
                I_bCl
                + (I_bCa + (I_NaL + (I_NaK + (I_NaCa + (I_Na + (I_Ks + (I_Kr + (I_CaL + I_K1))))))))
            )
        )
    )
    dcsl_dt = (1.0 * (J_e_sl + (J_RyR + (-J_sl_b - J_sl_c)))) / Vsl
    _linearization_temp_15 = 1 / Vsl
    _linearization_temp_16 = 1 / FoRT
    _linearization_temp_17 = csl**2
    _linearization_temp_18 = 1 / (KmPCa**2 + _linearization_temp_17)
    _linearization_temp_19 = Nao**3
    _linearization_temp_20 = nu - 1.0
    _linearization_temp_21 = FoRT * V_m
    _linearization_temp_22 = numpy.exp(_linearization_temp_20 * _linearization_temp_21)
    _linearization_temp_23 = Kdact**2
    _linearization_temp_24 = s1_sl - s2_sl
    _linearization_temp_25 = KmNao**3
    _linearization_temp_26 = csl / KmCai
    _linearization_temp_27 = 1 / s3_sl
    _linearization_temp_28 = Ka_sl * _linearization_temp_27
    _linearization_temp_29 = _linearization_temp_22 * ksat + 1.0
    _linearization_temp_30 = 1 / _linearization_temp_29
    _linearization_temp_31 = Q10NaCa**Qpow
    _linearization_temp_32 = _linearization_temp_30 * _linearization_temp_31 * g_NaCa
    _linearization_temp_33 = Cm * _linearization_temp_13 * chi
    dcsl_dt_linearized = (
        -1.0 * _linearization_temp_10 * _linearization_temp_15
        - 1.0
        * _linearization_temp_15
        * _linearization_temp_33
        * (
            1.0
            * Q10pCa**Qpow
            * _linearization_temp_18
            * csl
            * g_pCa
            * (-_linearization_temp_17 * _linearization_temp_18 + 1)
            + 0.25 * _linearization_temp_16 * g_bCa / csl
            - _linearization_temp_27
            * _linearization_temp_32
            * (
                -Ka_sl * _linearization_temp_19 * _linearization_temp_22
                + 2.0
                * _linearization_temp_23
                * _linearization_temp_24
                / (csl**3 * (1.0 + _linearization_temp_23 / _linearization_temp_17) ** 2)
                - _linearization_temp_24
                * _linearization_temp_28
                * (
                    _linearization_temp_19
                    + _linearization_temp_25 * _linearization_temp_26
                    + _linearization_temp_25 * (_linearization_temp_26 + 1.0)
                )
            )
        )
        - 1.0 * _linearization_temp_15 * alpha_sl_c
        - 1.0 * k_on_sl * (B_tot_sl - bsl)
    )
    values[22] = csl + numpy.where(
        numpy.logical_or((dcsl_dt_linearized > 1e-08), (dcsl_dt_linearized < -1e-08)),
        dcsl_dt * (numpy.exp(dcsl_dt_linearized * dt) - 1) / dcsl_dt_linearized,
        dcsl_dt * dt,
    )
    dNa_i_dt = J_Na
    _linearization_temp_34 = GNaL * hL * mL
    _linearization_temp_35 = _linearization_temp_16 / Na_i
    _linearization_temp_36 = g_Na * j * m**3
    _linearization_temp_37 = 9.0 * Na_i**2 * _linearization_temp_32
    _linearization_temp_38 = _linearization_temp_28 * ce * numpy.exp(_linearization_temp_21 * nu)
    _linearization_temp_39 = KmNaip**4.0 * Q10K_Nai ** (4.0 * Qpow)
    _linearization_temp_40 = Na_i ** (-4.0) * _linearization_temp_39 + 1.0
    _linearization_temp_41 = Ko * Q10NaK**Qpow * g_NaK / (KmKo + Ko)
    dNa_i_dt_linearized = -_linearization_temp_33 * (
        -Ka_sl
        * _linearization_temp_24
        * _linearization_temp_37
        * (KmCai * _linearization_temp_19 / KmNai**3 + KmCao + ce)
        / s3_sl**2
        + 12.0
        * Na_i ** (-5.0)
        * _linearization_temp_39
        * _linearization_temp_41
        * fNaK
        / _linearization_temp_40**2
        + _linearization_temp_34 * _linearization_temp_35
        + _linearization_temp_35 * _linearization_temp_36
        + _linearization_temp_37 * _linearization_temp_38
    )
    values[23] = Na_i + numpy.where(
        numpy.logical_or((dNa_i_dt_linearized > 1e-08), (dNa_i_dt_linearized < -1e-08)),
        dNa_i_dt * (numpy.exp(dNa_i_dt_linearized * dt) - 1) / dNa_i_dt_linearized,
        dNa_i_dt * dt,
    )
    dV_m_dt = -I_tot - i_Stim
    _linearization_temp_42 = numpy.sqrt(Ko)
    _linearization_temp_43 = 0.430331482911935 * _linearization_temp_42
    _linearization_temp_44 = numpy.exp(-0.1 * _linearization_temp_21)
    _linearization_temp_45 = 0.037 * sigma * numpy.exp(-_linearization_temp_21)
    _linearization_temp_46 = 1 / (aK1 + bK1)
    _linearization_temp_47 = numpy.exp(0.2 * V_m - 0.2 * ek)
    _linearization_temp_48 = _linearization_temp_46 * aK1
    _linearization_temp_49 = numpy.exp(-0.5 * V_m + 0.5 * ek)
    _linearization_temp_50 = 1 / (0.0820849986238988 * _linearization_temp_49 + 1.0)
    _linearization_temp_51 = numpy.exp(0.06 * V_m - 0.06 * ek)
    _linearization_temp_52 = numpy.exp(0.08 * V_m - 0.08 * ek)
    dV_m_dt_linearized = (
        FoRT
        * Ka_sl
        * _linearization_temp_19
        * _linearization_temp_20
        * _linearization_temp_22
        * _linearization_temp_27
        * _linearization_temp_30
        * _linearization_temp_31
        * csl
        * g_NaCa
        + FoRT
        * Ka_sl
        * _linearization_temp_20
        * _linearization_temp_22
        * _linearization_temp_24
        * _linearization_temp_27
        * _linearization_temp_31
        * g_NaCa
        * ksat
        / _linearization_temp_29**2
        - FoRT * Na_i**3 * _linearization_temp_32 * _linearization_temp_38 * nu
        - 1.0
        * FoRT
        * _linearization_temp_41
        * (0.012 * _linearization_temp_44 + _linearization_temp_45)
        / (
            _linearization_temp_40
            * (0.12 * _linearization_temp_44 + _linearization_temp_45 + 1.0) ** 2
        )
        - K1ss * _linearization_temp_43 * g_K1
        - Xr1 * Xr2 * _linearization_temp_43 * g_Kr
        + _linearization_temp_12
        * _linearization_temp_14
        * d
        * f
        * numpy.where(
            numpy.logical_and((V_m > -0.019306977288832503), (V_m < 0.019306977288832503)),
            FoRT
            * Frdy
            * g_CaL
            * (
                1.6653345369377348e-16 * FoRT**2 * V_m**2 * cd
                + 0.4533333333333334 * FoRT * V_m * cd
                - 0.4533333333333334 * FoRT * V_m * ce
                + 0.68 * cd
                + 0.68 * ce
            ),
            FoRT
            * Frdy
            * g_CaL
            * (
                -2.72
                * FoRT
                * V_m
                * (cd * numpy.exp(2.0 * FoRT * V_m) - ce)
                * numpy.exp(2.0 * FoRT * V_m)
                + (numpy.exp(2.0 * FoRT * V_m) - 1.0)
                * (
                    2.72 * FoRT * V_m * cd * numpy.exp(2.0 * FoRT * V_m)
                    + 1.36 * cd * numpy.exp(2.0 * FoRT * V_m)
                    - 1.36 * ce
                )
            )
            / (numpy.exp(2.0 * FoRT * V_m) - 1.0) ** 2,
        )
        - _linearization_temp_34
        - _linearization_temp_36
        + 0.430331482911935
        * _linearization_temp_42
        * _linearization_temp_46
        * g_K1
        * (V_m - ek)
        * (
            1.500911583015372e-06
            * _linearization_temp_47
            * (1 - _linearization_temp_48)
            / (7.50455791507686e-06 * _linearization_temp_47 + 1.0) ** 2
            + _linearization_temp_48
            * _linearization_temp_50
            * (
                0.0410424993119494
                * _linearization_temp_49
                * _linearization_temp_50
                * (
                    3.32464030033236e-16 * _linearization_temp_51
                    + 0.745912348820635 * _linearization_temp_52
                )
                + 1.9947841801994158e-17 * _linearization_temp_51
                + 0.059672987905650794 * _linearization_temp_52
            )
        )
        - g_Ks * x_Ks**2
        - g_bCa
        - g_bCl
        - g_f * xf
        - g_to * q * r
    )
    values[24] = V_m + numpy.where(
        numpy.logical_or((dV_m_dt_linearized > 1e-08), (dV_m_dt_linearized < -1e-08)),
        dV_m_dt * (numpy.exp(dV_m_dt_linearized * dt) - 1) / dV_m_dt_linearized,
        dV_m_dt * dt,
    )

    return values
